<Project Sdk="Aspire.AppHost.Sdk/13.5.2">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>472348ed-9627-4f46-b9b6-99ec7871d42d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.Azure.KeyVault" />
    <PackageReference Include="Aspire.Hosting.Azure.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mdsweep.Api\Mdsweep.Api.csproj" />
  </ItemGroup>
</Project>
