global using System.Text.Json.Serialization;
global using Ardalis.GuardClauses;
global using Ardalis.Result;
global using FluentValidation;
global using Mdsweep.Application.Common.Authorization;
global using Microsoft.AspNetCore.Antiforgery;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authentication.OpenIdConnect;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.HttpOverrides;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
global using NodaTime;
global using NodaTime.Serialization.SystemTextJson;
global using NodaTime.Text;
global using Wolverine;
global using Wolverine.Http;
global using ArdalisResult = Ardalis.Result;
global using ResultStatus = Ardalis.Result.ResultStatus;
global using ValidationError = Ardalis.Result.ValidationError;
