export const uiText = {
  productContext: 'NEMT operations',
  pageTitle: 'Today’s trips',
  signInTitle: 'Sign in',
  signInHelp: 'Use your Dispatcher account to manage today’s trips.',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  signingIn: 'Signing in…',
  uploadTitle: 'Upload MTM Manifest',
  uploadHelp: 'Choose the CSV downloaded from MTM. You can review problems before importing.',
  chooseCsv: 'Choose CSV',
  needsReview: 'Needs review',
  appointment: 'Appointment',
  passenger: 'Passenger',
  route: 'Pickup → destination',
  service: 'Service',
  status: 'Status',
} as const;
