global using System.Text;
global using System.Text.Json;
global using Ardalis.GuardClauses;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using NodaTime;
global using Wolverine;
