// <auto-generated />
using System;
using System.Collections.Generic;
using Mdsweep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mdsweep.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831065755_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:PostgresExtension:citext", ",,");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mdsweep.Domain.Passengers.PassengerAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerMemberId")
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BrokerMemberId")
                        .IsUnique();

                    b.ToTable("passengers", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("KeycloakOrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakOrganizationId")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "Role")
                        .IsUnique();

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.TripImports.TripImportAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ContentFingerprint")
                        .IsUnique()
                        .HasFilter("status = 'Applied'");

                    b.ToTable("trip_imports", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Trips.TripAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerTripNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<LocalTime?>("ScheduledPickupTime")
                        .HasColumnType("time");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TenantId", "BrokerTripNumber")
                        .IsUnique();

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Users.UserAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantMembership", b =>
                {
                    b.HasOne("Mdsweep.Domain.Tenants.TenantAggregate", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdsweep.Domain.Users.UserAggregate", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdsweep.Domain.TripImports.TripImportAggregate", b =>
                {
                    b.OwnsMany("Mdsweep.Domain.TripImports.TripImportItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AppliedTripId")
                                .HasColumnType("uuid");

                            b1.Property<LocalTime?>("AppointmentTime")
                                .HasColumnType("time");

                            b1.Property<string>("BrokerMemberId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("BrokerStatus")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Disposition")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("DropoffAddress")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("DropoffCity")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<bool>("IsWillCall")
                                .HasColumnType("boolean");

                            b1.Property<string>("LastName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("PickupAddress")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("PickupCity")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("RowNumber")
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("ServiceDate")
                                .HasColumnType("date");

                            b1.Property<Guid>("TripImportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TripNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<List<string>>("_messages")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("messages");

                            b1.HasKey("Id");

                            b1.HasIndex("TripImportId");

                            b1.ToTable("trip_import_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TripImportId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mdsweep.Domain.Trips.TripAggregate", b =>
                {
                    b.HasOne("Mdsweep.Domain.Passengers.PassengerAggregate", null)
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Mdsweep.Domain.Trips.BrokerTripFacts", "BrokerFacts", b1 =>
                        {
                            b1.Property<Guid>("TripAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<LocalTime?>("AppointmentTime")
                                .HasColumnType("time")
                                .HasColumnName("appointment_time");

                            b1.Property<string>("BrokerStatus")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("broker_status");

                            b1.Property<string>("DropoffAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_address");

                            b1.Property<string>("DropoffCity")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("dropoff_city");

                            b1.Property<bool>("IsWillCall")
                                .HasColumnType("boolean")
                                .HasColumnName("is_will_call");

                            b1.Property<string>("PickupAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_address");

                            b1.Property<string>("PickupCity")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("pickup_city");

                            b1.Property<DateOnly>("ServiceDate")
                                .HasColumnType("date")
                                .HasColumnName("service_date");

                            b1.HasKey("TripAggregateId");

                            b1.ToTable("trips");

                            b1.WithOwner()
                                .HasForeignKey("TripAggregateId");
                        });

                    b.Navigation("BrokerFacts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
