// <auto-generated />
using System;
using Mdsweep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mdsweep.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905005805_AddTripScheduling")]
    partial class AddTripScheduling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mdsweep.Domain.Passengers.PassengerAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrokerMemberId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broker_member_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BrokerMemberId")
                        .IsUnique();

                    b.ToTable("passengers", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("id");

                    b.Property<string>("KeycloakOrganizationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keycloak_organization_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakOrganizationId")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "Role")
                        .IsUnique();

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.TripImports.TripImportReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Added")
                        .HasColumnType("integer")
                        .HasColumnName("added");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Instant>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<int>("ProblemCount")
                        .HasColumnType("integer")
                        .HasColumnName("problem_count");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<int>("Unchanged")
                        .HasColumnType("integer")
                        .HasColumnName("unchanged");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.ToTable("trip_import_receipts", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Trips.TripAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrokerTripNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broker_trip_number");

                    b.Property<int?>("EstimatedTravelMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_travel_minutes");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<string>("ScheduledPickupSource")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("scheduled_pickup_source");

                    b.Property<LocalTime?>("ScheduledPickupTime")
                        .HasColumnType("time")
                        .HasColumnName("scheduled_pickup_time");

                    b.Property<string>("SchedulingInputFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scheduling_input_fingerprint");

                    b.Property<LocalTime?>("SuggestedPickupTime")
                        .HasColumnType("time")
                        .HasColumnName("suggested_pickup_time");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TenantId", "BrokerTripNumber")
                        .IsUnique();

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Users.UserAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keycloak_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantMembership", b =>
                {
                    b.HasOne("Mdsweep.Domain.Tenants.TenantAggregate", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mdsweep.Domain.Users.UserAggregate", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mdsweep.Domain.Trips.TripAggregate", b =>
                {
                    b.HasOne("Mdsweep.Domain.Passengers.PassengerAggregate", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Mdsweep.Domain.Trips.BrokerTripData", "BrokerData", b1 =>
                        {
                            b1.Property<Guid>("TripAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<LocalTime?>("AppointmentTime")
                                .HasColumnType("time")
                                .HasColumnName("appointment_time");

                            b1.Property<string>("BrokerStatus")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("broker_status");

                            b1.Property<string>("DropoffAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_address");

                            b1.Property<string>("DropoffCity")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("dropoff_city");

                            b1.Property<bool>("IsWillCall")
                                .HasColumnType("boolean")
                                .HasColumnName("is_will_call");

                            b1.Property<string>("MobilityRequirement")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("mobility_requirement");

                            b1.Property<string>("PickupAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_address");

                            b1.Property<string>("PickupCity")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("pickup_city");

                            b1.Property<string>("RawImportedPassengerType")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("raw_imported_passenger_type");

                            b1.Property<DateOnly>("ServiceDate")
                                .HasColumnType("date")
                                .HasColumnName("service_date");

                            b1.Property<decimal?>("TripCost")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("trip_cost");

                            b1.Property<decimal?>("TripMileage")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("trip_mileage");

                            b1.HasKey("TripAggregateId");

                            b1.ToTable("trips");

                            b1.WithOwner()
                                .HasForeignKey("TripAggregateId");
                        });

                    b.Navigation("BrokerData")
                        .IsRequired();

                    b.Navigation("Passenger");
                });
#pragma warning restore 612, 618
        }
    }
}
