// <auto-generated />
using System;
using Mdsweep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mdsweep.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mdsweep.Domain.Passengers.PassengerAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrokerMemberId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broker_member_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_passengers");

                    b.HasIndex("TenantId", "BrokerMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_passengers_tenant_id_broker_member_id");

                    b.ToTable("passengers", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("id");

                    b.Property<string>("DefaultSenderEmail")
                        .HasColumnType("text")
                        .HasColumnName("default_sender_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PickupBufferMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("pickup_buffer_minutes");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_memberships_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_memberships_tenant_id_user_id");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Trips.TripAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrokerTripNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broker_trip_number");

                    b.Property<LocalTime?>("CalculatedPickupTime")
                        .HasColumnType("time")
                        .HasColumnName("calculated_pickup_time");

                    b.Property<int?>("EstimatedDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_distance_meters");

                    b.Property<int?>("EstimatedTravelMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_travel_minutes");

                    b.Property<LocalTime?>("ManualPickupTime")
                        .HasColumnType("time")
                        .HasColumnName("manual_pickup_time");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("PassengerId")
                        .HasDatabaseName("ix_trips_passenger_id");

                    b.HasIndex("TenantId", "BrokerTripNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_trips_tenant_id_broker_trip_number");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Users.InvitationAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_invitations_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_tenant_id_email")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Users.UserAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keycloak_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Mdsweep.Domain.Tenants.TenantMembership", b =>
                {
                    b.HasOne("Mdsweep.Domain.Tenants.TenantAggregate", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("Mdsweep.Domain.Users.UserAggregate", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_users_user_id");
                });

            modelBuilder.Entity("Mdsweep.Domain.Trips.TripAggregate", b =>
                {
                    b.HasOne("Mdsweep.Domain.Passengers.PassengerAggregate", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_passengers_passenger_id");

                    b.OwnsOne("Mdsweep.Domain.Trips.BrokerTripData", "BrokerData", b1 =>
                        {
                            b1.Property<Guid>("TripAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<LocalTime?>("AppointmentTime")
                                .HasColumnType("time")
                                .HasColumnName("appointment_time");

                            b1.Property<LocalTime?>("BrokerPickupTime")
                                .HasColumnType("time")
                                .HasColumnName("broker_pickup_time");

                            b1.Property<decimal?>("Cost")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("trip_cost");

                            b1.Property<int>("Direction")
                                .HasColumnType("integer")
                                .HasColumnName("direction");

                            b1.Property<string>("DropoffAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_address");

                            b1.Property<string>("DropoffCity")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("dropoff_city");

                            b1.Property<string>("DropoffState")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("dropoff_state");

                            b1.Property<string>("DropoffZip")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("dropoff_zip");

                            b1.Property<bool>("IsWillCall")
                                .HasColumnType("boolean")
                                .HasColumnName("is_will_call");

                            b1.Property<decimal?>("Mileage")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("trip_mileage");

                            b1.Property<string>("PassengerType")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("passenger_type");

                            b1.Property<string>("PickupAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_address");

                            b1.Property<string>("PickupCity")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("pickup_city");

                            b1.Property<string>("PickupState")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("pickup_state");

                            b1.Property<string>("PickupZip")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("pickup_zip");

                            b1.Property<LocalDate>("ServiceDate")
                                .HasColumnType("date")
                                .HasColumnName("service_date");

                            b1.Property<string>("SpecialNeeds")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("special_needs");

                            b1.Property<string>("Status")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("broker_status");

                            b1.HasKey("TripAggregateId");

                            b1.ToTable("trips");

                            b1.WithOwner()
                                .HasForeignKey("TripAggregateId")
                                .HasConstraintName("fk_trips_trips_id");
                        });

                    b.Navigation("BrokerData")
                        .IsRequired();

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Mdsweep.Domain.Users.InvitationAggregate", b =>
                {
                    b.HasOne("Mdsweep.Domain.Tenants.TenantAggregate", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
