export const uiText = {
  productContext: 'NEMT operations',
  pageTitle: 'Today’s trips',
  signInTitle: 'Sign in',
  signInHelp: 'Use your MDSweep account to continue.',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  signingIn: 'Signing in…',
  uploadTitle: 'Import Trips',
  uploadHelp: 'Upload the trip file you received from MTM.',
  chooseManifest: 'Choose File',
  needsReview: 'Needs review',
  newTrips: 'new',
  brokerChanged: 'changed by MTM',
  unchanged: 'unchanged',
  locallyOverridden: 'provider schedules protected',
  inactive: 'inactive',
  appointment: 'Appointment',
  scheduledPickup: 'Scheduled pickup',
  save: 'Save',
  scheduleSaveError: 'Unable to save the scheduled pickup time.',
  passenger: 'Passenger',
  route: 'Pickup → destination',
  service: 'Service',
  status: 'Status',
} as const;
