<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mdsweep.Api\Mdsweep.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Fixtures/**" CopyToOutputDirectory="PreserveNewest" />
    <None
      Include="../../src/Mdsweep.AppHost/keycloak/mdsweep-realm.json"
      Link="Fixtures/keycloak/mdsweep-realm.json"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
